#  ssl:
#    enabled: true
#    key-alias: gateway-ssl
#    key-store-password: Undefinable##LordsOf{Th@R$ING$Z}
#    key-store: classpath:gateway-ssl.p12
#    key-store-type: PKCS12

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: authService
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/channel/oauth/**
          filters:
            - RewritePath=/channel/(?<segment>.*), /${segment}

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/channel/api/v1/admin/**
          filters:
            - RewritePath=/channel/(?<segment>.*), /${segment}

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/channel/api/portal/category/**
            - Path=/channel/api/portal/product/**
            - Path=/channel/api/v1/mobile/products/**
          filters:
            - RewritePath=/channel/(?<segment>.*), /${segment}
key:
  name: channel-auth-ssl.p12
  alias: channel-auth-ssl
  password: LordsOf{Th@R$ING$Z}

eureka:
  instance:
    prefer-ip-address: true
  client:
    prefer-same-zone-eureka: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://10.20.2.201:7601/eureka
    fetch-registry: true
    enabled: off

logging:
  file:
    name: ./logs/${spring.application.name}.log
IP:
  WHITELIST: https://10.20.2.201
  WHITELIST-ON: off

services:
  integration:
    basic:
      client: channel-service
      password: C-sg6OGT4/*8Cy4=
login:
  endpoints:
    validate: http://10.20.2.201:7602/oauth/validate