#  ssl:
#    enabled: true
#    key-alias: gateway-ssl
#    key-store-password: Undefinable##LordsOf{Th@R$ING$Z}
#    key-store: classpath:gateway-ssl.p12
#    key-store-type: PKCS12

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: authService
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/oauth/**
          filters:
            - RewritePath=/channel/(?<path>.*), /$\{path}

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/admin/**
          filters:
            - RewritePath=/channel/(?<path>.*), /$\{path}

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/portal/category/**
            - Path=/api/portal/product/**
            - Path=/api/v1/mobile/products/**
          filters:
            - RewritePath=/channel/(?<path>.*), /$\{path}

eureka:
  instance:
    prefer-ip-address: true
  client:
    prefer-same-zone-eureka: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${server-ip}:7601/eureka
    fetch-registry: true
    enabled: on

logging:
  file:
    name: ./logs/${spring.application.name}.log
IP:
  WHITELIST: https://10.20.2.19
  WHITELIST-ON: off
