server:
  port: 7600
#  ssl:
#    enabled: true
#    key-alias: gateway-ssl
#    key-store-password: Undefinable##LordsOf{Th@R$ING$Z}
#    key-store: classpath:gateway-ssl.p12
#    key-store-type: PKCS12

spring:
  application:
    name: api-gateway

#logging:
#  file:
#    path: /logs
#    name: ${spring.application.name}.log

eureka:
  instance:
    prefer-ip-address: true
  client:
    prefer-same-zone-eureka: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://10.20.2.19:7601/eureka
    fetch-registry: true
    enabled: on

IP:
  WHITELIST: https://localhost
  WHITELIST-ON: off
