server:
  port: 9700
  ssl:
    enabled: true
    key-alias: gateway-ssl
    key-store-password: Undefinable##LordsOf{Th@R$ING$Z}
    key-store: classpath:gateway-ssl.p12
    key-store-type: PKCS12

spring:
  application:
    name: api-gateway

#logging:
#  file:
#    path: /logs
#    name: ${spring.application.name}.log

eureka:
  instance:
    prefer-ip-address: true
  client:
    prefer-same-zone-eureka: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:9713/eureka
    fetch-registry: true
    enabled: on


routes:
  AUTH-SERVER: auth-server
  WORKFLOW: workflow-service
IP:
  WHITELIST: https://test-portal.ekenya.co.ke, http://10.20.2.12
