version: '3.7'
services:
  gateway-service:
    build: .
    hostname: gateway-service
    container_name: channel-gateway
    restart: always
    volumes:
      - ./GatewayLogs:/app/logs
    ports:
      - "7600:7600"
    networks:
      - channel-net
    deploy:
      resources:
        limits:
          memory: 256M
networks:
  channel-net:
    name: channel-net
    driver: bridge
    external: true