version: '3.7'
services:
  gateway-service:
    image: devops-registry.ekenya.co.ke/channel-manager/channel-gateway:latest
    hostname: gateway-service
    container_name: channel-gateway
    restart: always
    volumes:
      - ./GatewayLogs:/app/logs
    ports:
      - "7600:7600"
    environment:
      - server-ip=10.20.2.201
    networks:
      - channel-net
    deploy:
      resources:
        limits:
          memory: 256M
networks:
  channel-net:
    name: channel-net
    driver: bridge
    external: true